feat: add rewards calculation
lidofinance/polygon-validators-monitoring pull request #33
Opened 2023-02-14 11:36 UTC by madlabman

2023-02-14 12:42 UTC, dgusakov approved these changes

2023-02-15 10:08 UTC, vgorkavenko requested changes

2023-02-15 10:14 UTC, madlabman commented on src/checkpoints/checkpoints.service.ts
> +    checkpoint.rewards = [];
`reward` is a checkpoint total reward, where `rewards` are the related entities basically, read as reward for the every validator in active set.

2023-02-15 10:22 UTC, vgorkavenko commented on src/checkpoints/checkpoints.service.ts
> +    checkpoint.rewards = [];
Name them according to your description. Because now without context, I think it is not clear to others

2023-02-15 10:43 UTC, madlabman commented on src/checkpoints/checkpoints.service.ts
> +    checkpoint.rewards = [];
Updated.

2023-02-15 11:32 UTC, vgorkavenko approved these changes

2023-02-15 12:13 UTC, merged